# Generated by Django 3.2.9 on 2021-12-19 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Enemy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=10)),
                ('damage', models.IntegerField()),
                ('speed', models.IntegerField()),
                ('health', models.IntegerField()),
            ],
        ),
    ]
