# Generated by Django 3.2.9 on 2022-01-30 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataapp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='enemy',
            name='avatar',
            field=models.ImageField(blank=True, upload_to=''),
        ),
    ]
